set nocompatible              " be iMproved, required
filetype off                  " required

" Highlight unwanted whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Highlight column 80
set colorcolumn=80

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'wombat256.vim'
Plugin 'taskpaper.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'scala.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
" Put your non-Plugin stuff after this line

set term=xterm-256color
syntax on
colorscheme wombat256mod

set tabstop=4
set shiftwidth=4
set expandtab

set ruler

" Custom filetype handling/hacking
autocmd BufRead,BufNewFile *.scala set filetype=scala
autocmd FileType scala setlocal shiftwidth=2 tabstop=2

